test = {   'hidden': False,
    'name': 'q1',
    'points': 10,
    'suites': [   {   'cases': [   {   'code': '>>> square_num(2)\n4',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
