test = {   'hidden': False,
    'name': 'q4b',
    'points': 10,
    'suites': [   {   'cases': [   {   'code': '>>> \n'
                                               '>>> '
                                               "print(fullaqi.index.get_level_values('County').unique().to_list())\n"
                                               "['Jefferson', 'Madison', "
                                               "'Anchorage ', 'Maricopa', "
                                               "'Pima', 'Pulaski', 'Union', "
                                               "'Alameda', 'Butte', 'Contra "
                                               "Costa', 'El Dorado', 'Fresno', "
                                               "'Imperial', 'Kern', 'Los "
                                               "Angeles', 'Marin', 'Mariposa', "
                                               "'Monterey', 'Napa', 'Orange', "
                                               "'Placer', 'Riverside', "
                                               "'Sacramento', 'San Benito', "
                                               "'San Bernardino', 'San Diego', "
                                               "'San Francisco', 'San "
                                               "Joaquin', 'San Luis Obispo', "
                                               "'San Mateo', 'Santa Barbara', "
                                               "'Santa Clara', 'Santa Cruz', "
                                               "'Shasta', 'Solano', 'Sonoma', "
                                               "'Stanislaus', 'Sutter', "
                                               "'Tulare', 'Ventura', 'Adams', "
                                               "'Denver', 'El Paso', "
                                               "'Larimer', 'Mesa', 'Weld', "
                                               "'Fairfield', 'Hartford', 'New "
                                               "Haven', 'New Castle', "
                                               "'District of Columbia', "
                                               "'Brevard', 'Broward', 'Duval', "
                                               "'Escambia', 'Hillsborough', "
                                               "'Lee', 'Miami-Dade', 'Palm "
                                               "Beach', 'Pinellas', 'Polk', "
                                               "'Sarasota', 'Seminole', "
                                               "'Chatham', 'DeKalb', 'Floyd', "
                                               "'Fulton', 'Honolulu', "
                                               "'Champaign', 'Cook', 'Kane', "
                                               "'Lake', 'Macon', 'Macoupin', "
                                               "'Peoria', 'Rock Island', "
                                               "'Saint Clair', 'Sangamon', "
                                               "'Will', 'Winnebago', 'Allen', "
                                               "'Daviess', 'Knox', 'Marion', "
                                               "'Porter', 'Vanderburgh', "
                                               "'Vigo', 'Clinton', 'Linn', "
                                               "'Muscatine', 'Scott', "
                                               "'Sedgwick', 'Wyandotte', "
                                               "'Boyd', 'Edmonson', 'Fayette', "
                                               "'Henderson', 'McCracken', "
                                               "'Bossier', 'Caddo', "
                                               "'Calcasieu', 'East Baton "
                                               "Rouge', 'Iberville', "
                                               "'Lafayette', 'Pointe Coupee', "
                                               "'St. James', 'St. John the "
                                               "Baptist', 'West Baton Rouge', "
                                               "'Aroostook', 'Penobscot', "
                                               "'Baltimore', 'Baltimore "
                                               '(City)\', "Prince George\'s", '
                                               "'Bristol', 'Essex', 'Hampden', "
                                               "'Hampshire', 'Middlesex', "
                                               "'Suffolk', 'Worcester', "
                                               "'Kent', 'Wayne', 'Anoka', "
                                               "'Dakota', 'Hennepin', "
                                               "'Ramsey', 'Saint Louis', "
                                               "'Washington', 'Harrison', "
                                               "'Hinds', 'Clay', 'Greene', "
                                               "'Jackson', 'Monroe', 'St. "
                                               "Louis City', 'Cascade', "
                                               "'Flathead', 'Rosebud', 'Silver "
                                               "Bow', 'Yellowstone', "
                                               "'Douglas', 'Clark', 'Washoe', "
                                               "'Merrimack', 'Rockingham', "
                                               "'Atlantic', 'Camden', "
                                               "'Cumberland', 'Hudson', "
                                               "'Hunterdon', 'Mercer', "
                                               "'Morris', 'Bernalillo', 'Dona "
                                               "Ana', 'San Juan', 'Sandoval', "
                                               "'Santa Fe', 'Albany', 'Bronx', "
                                               "'Chautauqua', 'Erie', 'Kings', "
                                               "'New York', 'Onondaga', "
                                               "'Westchester', 'Forsyth', "
                                               "'Guilford', 'Mecklenburg', "
                                               "'Wake', 'McKenzie', "
                                               "'Williams', 'Ashtabula', "
                                               "'Butler', 'Cuyahoga', "
                                               "'Franklin', 'Hamilton', "
                                               "'Lawrence', 'Lucas', "
                                               "'Mahoning', 'Montgomery', "
                                               "'Scioto', 'Stark', 'Summit', "
                                               "'Cleveland', 'Muskogee', "
                                               "'Oklahoma', 'Tulsa', 'Lane', "
                                               "'Multnomah', 'Allegheny', "
                                               "'Beaver', 'Blair', 'Bucks', "
                                               "'Cambria', 'Dauphin', "
                                               "'Delaware', 'Lackawanna', "
                                               "'Lancaster', 'Lehigh', "
                                               "'Luzerne', 'Northampton', "
                                               "'Philadelphia', 'York', "
                                               "'Providence', 'Charleston', "
                                               "'Richland', 'Blount', "
                                               "'Davidson', 'Shelby', "
                                               "'Sullivan', 'Bexar', 'Dallas', "
                                               "'Denton', 'Galveston', "
                                               "'Harris', 'Nueces', 'Tarrant', "
                                               "'Travis', 'Davis', 'Salt "
                                               "Lake', 'Utah', 'Weber', "
                                               "'Chittenden', 'Fairfax', "
                                               "'Roanoke', 'Clallam', 'King', "
                                               "'Pierce', 'Skagit', "
                                               "'Snohomish', 'Spokane', "
                                               "'Brooke', 'Hancock', "
                                               "'Kanawha', 'Monongalia', "
                                               "'Wood', 'Brown', "
                                               "'Milwaukee']\n",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> \n'
                                               ">>> fullaqi['Median "
                                               "AQI'].sum()\n"
                                               '375892',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> \n'
                                               '>>> print(worst_counties)\n'
                                               "[('Alabama', 'Jefferson') "
                                               "('Alaska', 'Anchorage ') "
                                               "('Arizona', 'Maricopa')\n"
                                               " ('Arkansas', 'Pulaski') "
                                               "('California', 'San "
                                               "Bernardino')\n"
                                               " ('Colorado', 'Denver') "
                                               "('Connecticut', 'New Haven')\n"
                                               " ('Delaware', 'New Castle')\n"
                                               " ('District Of Columbia', "
                                               "'District of Columbia')\n"
                                               " ('Florida', 'Hillsborough') "
                                               "('Georgia', 'Fulton') "
                                               "('Hawaii', 'Honolulu')\n"
                                               " ('Illinois', 'Madison') "
                                               "('Indiana', 'Marion') ('Iowa', "
                                               "'Scott')\n"
                                               " ('Kansas', 'Wyandotte') "
                                               "('Kentucky', 'Jefferson')\n"
                                               " ('Louisiana', 'East Baton "
                                               "Rouge') ('Maine', "
                                               "'Aroostook')\n"
                                               " ('Maryland', 'Baltimore "
                                               "(City)') ('Massachusetts', "
                                               "'Suffolk')\n"
                                               " ('Michigan', 'Wayne') "
                                               "('Minnesota', 'Hennepin') "
                                               "('Mississippi', 'Hinds')\n"
                                               " ('Missouri', 'St. Louis "
                                               "City') ('Montana', "
                                               "'Yellowstone')\n"
                                               " ('Nebraska', 'Douglas') "
                                               "('Nevada', 'Clark')\n"
                                               " ('New Hampshire', "
                                               "'Hillsborough') ('New Jersey', "
                                               "'Union')\n"
                                               " ('New Mexico', 'Dona Ana') "
                                               "('New York', 'New York')\n"
                                               " ('North Carolina', "
                                               "'Mecklenburg') ('North "
                                               "Dakota', 'Mercer')\n"
                                               " ('Ohio', 'Cuyahoga') "
                                               "('Oklahoma', 'Tulsa') "
                                               "('Oregon', 'Jackson')\n"
                                               " ('Pennsylvania', 'Allegheny') "
                                               "('Rhode Island', "
                                               "'Providence')\n"
                                               " ('South Carolina', "
                                               "'Richland') ('Tennessee', "
                                               "'Sullivan')\n"
                                               " ('Texas', 'El Paso') ('Utah', "
                                               "'Salt Lake') ('Vermont', "
                                               "'Chittenden')\n"
                                               " ('Virginia', 'Fairfax') "
                                               "('Washington', 'Spokane')\n"
                                               " ('West Virginia', 'Hancock') "
                                               "('Wisconsin', 'Milwaukee')]\n",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> \n'
                                               '>>> '
                                               'set(worstaqi.columns.to_list()) '
                                               '- set(cols)\n'
                                               "{'County', 'State'}",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
